<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<jsp:include page="WEB-INF/views/fragments/header.jsp">
    <jsp:param name="pageTitle" value="GenZ Beats - Âm nhạc cho thế hệ mới" />
</jsp:include>

    <!-- Loading Screen -->
    <div class="loader" id="loader">
        <div class="loader-content">
            <div class="loader-prism">
                <div class="prism-face"></div>
                <div class="prism-face"></div>
                <div class="prism-face"></div>
            </div>
            <div style="color: var(--accent-purple); font-size: 18px; text-transform: uppercase; letter-spacing: 3px;">Loading Music...</div>
        </div>
    </div>

    <!-- Featured Singers Carousel -->
    <section class="hero" id="singers">
        <div class="carousel-container">
            <div class="carousel" id="carousel">
                <!-- Carousel items will be generated by JavaScript -->
            </div>
            
            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>
            
            <div class="carousel-indicators" id="indicators">
                <!-- Indicators will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Music Genres Section -->
    <section class="philosophy-section" id="genres">
        <div class="philosophy-container">
            <div class="prism-line"></div>
            
            <h2 class="philosophy-headline">
                Thể loại<br>Âm nhạc
            </h2>
            
            <p class="philosophy-subheading">
                Khám phá kho nhạc đa dạng từ V-POP, US-UK, EDM, Lo-fi, Rap Việt đến Acoustic. Mỗi thể loại là một thế giới âm thanh riêng biệt.
            </p>
            
            <div class="philosophy-pillars">
                <div class="pillar">
                    <div class="pillar-icon">🎧</div>
                    <h3 class="pillar-title">V-POP & Ballad</h3>
                    <p class="pillar-description">
                        Những bản hit Việt nổi bật, lời ca sâu lắng, giai điệu cuốn hút — cập nhật liên tục mỗi tuần.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon"><i class='bx bx-volume-full'></i></div>
                    <h3 class="pillar-title">EDM & Dance</h3>
                    <p class="pillar-description">
                        Năng lượng bùng nổ, bass mạnh mẽ — playlist hoàn hảo cho buổi tối cuối tuần và workout.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon"><i class='bx bx-music'></i></div>
                    <h3 class="pillar-title">Lo-fi & Chill</h3>
                    <p class="pillar-description">
                        Nhạc nhẹ nhàng, mộc mạc cho học tập, làm việc và thư giãn — tạo không gian yên bình cho tâm hồn.
                    </p>
                </div>
            </div>
            
            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Trending Music Section -->
    <section class="stats-section" id="trending">
        <div class="section-header">
            <h2 class="section-title">Trending & Thống kê</h2>
            <p class="section-subtitle">Cập nhật BXH, lượt nghe và xu hướng âm nhạc mới nhất</p>
        </div>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon"><i class='bx bx-music'></i></div>
                <div class="stat-number" data-target="5000">0</div>
                <div class="stat-label">Bài hát</div>
                <p class="stat-description">Kho nhạc khổng lồ từ V-POP, US-UK, EDM, Lo-fi đến Rap Việt — cập nhật liên tục.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon"><i class='bx bx-microphone'></i></div>
                <div class="stat-number" data-target="500">0</div>
                <div class="stat-label">Ca sĩ nổi tiếng</div>
                <p class="stat-description">Theo dõi các nghệ sĩ yêu thích, khám phá bài hát mới từ họ mỗi ngày.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon"><i class='bx bxs-hot'></i></div>
                <div class="stat-number" data-target="100">0</div>
                <div class="stat-label">Playlist hot</div>
                <p class="stat-description">Danh sách phát được tuyển chọn kỹ lưỡng cho mọi tâm trạng và hoạt động.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon"><i class='bx bx-group'></i></div>
                <div class="stat-number" data-target="1000">0</div>
                <div class="stat-label">Người dùng</div>
                <p class="stat-description">Cộng đồng GenZ yêu nhạc đang phát triển mỗi ngày — tham gia ngay!</p>
            </div>
        </div>
    </section>

    <!-- CTA Section -->
    <section class="contact-section" id="cta">
        <div class="section-header">
            <h2 class="section-title">Bắt đầu hành trình âm nhạc</h2>
            <p class="section-subtitle">Đăng ký để lưu bài hát yêu thích, tạo playlist và khám phá thêm nhiều tính năng</p>
        </div>
        
        <div style="text-align:center; padding: 3rem 0;">
            <c:choose>
                <c:when test="${not empty sessionScope.user}">
                    <a href="${ctx}/home" style="display:inline-block; padding:1rem 3rem; background:linear-gradient(90deg,#7a5cff,#00c2ff 70%); color:#fff; border-radius:50px; text-decoration:none; font-size:1.2rem; font-weight:700;">Khám phá nhạc mới</a>
                </c:when>
                <c:otherwise>
                    <a href="${ctx}/register" style="display:inline-block; padding:1rem 3rem; background:linear-gradient(90deg,#7a5cff,#00c2ff 70%); color:#fff; border-radius:50px; text-decoration:none; font-size:1.2rem; font-weight:700; margin-right:1rem;">Đăng ký miễn phí</a>
                    <a href="${ctx}/login" style="display:inline-block; padding:1rem 3rem; background:rgba(255,255,255,0.1); color:#fff; border:2px solid #7a5cff; border-radius:50px; text-decoration:none; font-size:1.2rem; font-weight:700;">Đăng nhập</a>
                </c:otherwise>
            </c:choose>
        </div>
    </section>

<jsp:include page="WEB-INF/views/fragments/footer.jsp" />
<script>window.APP_CONTEXT='${ctx}';</script>
<script src="${ctx}/index.js"></script>
<script>
// Ẩn loading screen khi trang load xong
(function() {
    function hideLoader() {
        const loader = document.getElementById('loader');
        if (loader) {
            loader.style.opacity = '0';
            loader.style.transition = 'opacity 0.5s ease';
            setTimeout(function() {
                loader.style.display = 'none';
            }, 500);
        }
    }
    
    // Thử ẩn ngay khi script chạy (DOM đã ready)
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', function() {
            setTimeout(hideLoader, 300);
        });
    } else {
        setTimeout(hideLoader, 300);
    }
    
    // Fallback: Ẩn khi window.load
    window.addEventListener('load', function() {
        setTimeout(hideLoader, 500);
    });
})();
</script>